### ISSUE TITLE
贝壳频繁出现验证码怎么解决

### ISSUE THREAD

**Issue by aming-zi** [tree-branch/house#3]

**Comment by tree-branch** [comment]
尽量用邮箱联系我，issues我一般不看

**Comment by tree-branch** [comment]
什么样的情况？我这正常使用没有出现验证码，可以详细说说吗？

**Comment by aming-zi** [comment]
多谢，已经解决了，访问频繁就会出现点选验证码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tree-branch/house"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 中午11:09
收件人:&nbsp;"tree-branch/house"<house@noreply.github.com&gt;;
抄送:&nbsp;"大明纸"<zzmman@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tree-branch/house] 贝壳频繁出现验证码怎么解决 (#3)





 
什么样的情况？我这正常使用没有出现验证码，可以详细说说吗？
