### ISSUE TITLE
请问lianjia 信息 “positionInfo”  中的后半段怎样也加到 villageName 里

### ISSUE THREAD

**Issue by zhm-nico-nico-ni** [tree-branch/house#5]
如：
`<div class="positionInfo"><span class="positionIcon"></span><a href="https://gz.lianjia.com/xiaoqu/2110343238336681/" target="_blank" data-log_index="1" data-el="region">华南新城 </a>   -  <a href="https://gz.lianjia.com/ershoufang/huananxincheng/" target="_blank">番禺区</a> </div>`

原代码：
        elif tag == "a" and ("data-el", "region") in attrs:
            self.flag.append("villageName")

怎样把后面的 target="_blank" 加上呢。

我新手，可否赐教

**Comment by tree-branch** [comment]
不能一起获取到，可以再命名成villageName2。然后遇到villageName2的追加到vallageName[-1]里。
elif tag == "a" and ("target", "_blank") in attrs:
self.flag.append("villageName2")
另外发邮件的话，我回的会快点。今天是没啥事我才来看一下。

**Comment by zhm-nico-nico-ni** [comment]
谢谢指点，我这边是用全局变量标记，把后面的“番禺区” 加到 villageName 中的。

第一段
```
        #原代码 部分
        elif tag == "a" and ("data-el", "region") in attrs:
            self.flag.append("villageName")
            lastIsVillageName = 1
        #原代码 部分 end
        **elif (lastIsVillageName == 1) and tag == "a" and ("target", "_blank") in attrs:
            self.flag.append("villageName2")
            lastIsVillageName = 0**
```

第二段
```
        #原代码 部分
        elif self.flag[-1] == "villageName":
                # print(str(data))
                self.villageName.append(data)
                self.flag.pop()
        #原代码 部分 end
        **elif self.flag[-1] == "villageName2":
                # print(str(data))
                temp1 = self.villageName.pop()
                temp =  data + "-" + temp1
                # temp = temp1 + "-"+data
                self.villageName.append(temp)
                self.flag.pop()**
```


问题已解决
