### ISSUE TITLE
ValueError: 数据个数不一致

### ISSUE THREAD

**Issue by erek303** [tree-branch/house#6]
ValueError: 数据个数不一致：houseName-0,villageName-30,houseNote-30,houseTotlePrice-0,houseUnitPrice-30,houseLink-0,houseImg-30,followNum-30
你好，这个情况是什么原因呢

**Comment by tree-branch** [comment]
可能是网页升级了，是用我里边的例子报错 还是 你自己的网址报错。把你的网址发给我，和报错信息。也可以和我邮件联系，那样快一些。

**Comment by shuo-1106** [comment]
ValueError("数据个数不一致：：houseName-" + str(len(self.houseName)) + ",villageName-" + str(len(self.villageName)) +
ValueError: 数据个数不一致：houseName-0,villageName-30,houseNote-30,houseTotlePrice-0,houseUnitPrice-30,houseLink-0,houseImg-30,followNum-30 
我同样遇到了这个问题，请问大佬是怎么解决的

**Comment by tree-branch** [comment]
可能是链接解析的不正确。把你的链接发给我 或者 你修改之后的house.py发给我。

----- 原始邮件 -----
发件人：shuo-1106 ***@***.***>
收件人：tree-branch/house ***@***.***>
抄送人：tree-branch ***@***.***>,  Comment ***@***.***>
主题：Re:_[tree-branch/house]_ValueError:_数据个数不一致_(Issue_#6)
日期：2023年02月07日 19点17分



ValueError("数据个数不一致：：houseName-" + str(len(self.houseName)) + ",villageName-" + str(len(self.villageName)) +


ValueError: 数据个数不一致：houseName-0,villageName-30,houseNote-30,houseTotlePrice-0,houseUnitPrice-30,houseLink-0,houseImg-30,followNum-30


我同样遇到了这个问题，请问大佬是怎么解决的
